/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  ******************************************************************************
*/

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
#include<stdint.h>		// for typecasting
#define alias_base 			0x22000000u			// from datasheet
#define bitband_base 		0x20000000u			// from datasheet
#define bit					7
#define bitband_mem_adr 	0x20000200u
int main(void)
{
	//value at 0x20000200
	uint8_t *ptr=(uint8_t *)0x20000200;

	*ptr=0xFF;// the address above: 0x20000200 contains the value of 0xFF

	// without bitbanding
	*ptr &=~(1<<7); // the 7th bit is cleared for the value of ptr which is 0xFF

	// reset value of ptr
	*ptr=0xFF;

	// with bitbanding
	// calculate the alias address of the 7th bit
	uint8_t *alias_addr=(uint8_t *)(alias_base + (32* (bitband_mem_adr - bitband_base))+ (4*bit));

	//printf("%lld",alias_addr);

	// clear 7th bit
	*alias_addr=0;
	for(;;);
}
