/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  ******************************************************************************
*/

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	// The program intends to load values from memory, perform an operation and store in back in the registers
	// this cannot be achieved directly
	// Inline assembly code is used

	__asm volatile("LDR R1,=#0x20001000");// load r1 with the value from the location 0x20001000
	__asm volatile("LDR R2,=#0x20001004");// load r2 with the value from the location 0x20001004
	__asm volatile("LDR R0,[R1]");	// loading the value into R0 from memory location R1
	__asm volatile("LDR R1,[R2]");
	__asm volatile("ADD R0,R0,R1");// add the values from R0 and R1 and store it in R0
	__asm volatile("STR R0,[R2]");// store value of R0 in the memory location pointed to by R1


	for(;;);
}
