/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  ******************************************************************************
*/

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	// generate the variable to store the value of the control register
	//int control_info;
	//__asm volatile("MRS %0,CONTROL":"=r"(control_info)::);//=r is for output operand
	// 0800020a:   mrs     r3, CONTROL
	// 0800020e:   str     r3, [r7, #4] r7 contains address of control_info

	// store value of one c variable in another
	//int x=10,y; // store value of x in y
	//__asm volatile("MOV %0,%1":"=r"(y):"r"(x):);
	// 0800020a:   movs    r3, #10
	// 0800020c:   str     r3, [r7, #4]

	// Copy value of pointer in another pointer
	int p1,p2;
	p2=(int *)0x20000008;
	__asm volatile("LDR %0,[%1]":"=r"(p1):"r"(p2):);

	for(;;);
}
