/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  ******************************************************************************
*/

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	// objective here is to move the value stored in a 'C' variable to the ARM Register
	//int val=20;
	//__asm volatile("MOV R0,%0"::"r"(val));// %0 is taking the first value(which is the input since output operand list is not used
	// 17        	int val=20;
	//0800020a:   movs    r3, #20
	//0800020c:   str     r3, [r7, #4]
	// the above instrcution generated in assembly by using "r" which uses registers to transfer value

	__asm volatile("MOV R0,%0"::"I"(0x13));
	// 08000208:   mov.w   r0, #19 the value is directly stored
	for(;;);
}
