/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  ******************************************************************************
*/

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include<stdio.h>
#include<stdint.h>


int main(void)
{
	__asm("SVC #8"); // svc number 8

}

__attribute__((naked)) void SVC_Handler(void)
{
	__asm("MRS R0,MSP");
	__asm("B SVC_Handler_c");// value of R0 copied to baseStack , the argument holds the address of R0 - by Procedure call

	register uint32_t data __asm("r0");
	printf("Data = %d\n",data);
}
void SVC_Handler_c(uint32_t *baseStack)
{
	printf("in SVC Handler \n");
	// retrieve the address of the PC
	uint8_t *pReturn_addr=(uint8_t *)baseStack[6]; // point to the 6th value stored in the baseStack array

	// decrement the address by 2 to point to the opcode of SVC instruction
	pReturn_addr -2 ;

	// print the svc number obtained
	uint8_t svc_number=*pReturn_addr;
	printf("SVC number is %d\n",svc_number);

	// increment the SVC number by 4
	svc_number +=4;

	// the value of the svc number can be saved in R0 which is a part of the MSP[0th]
	// when the MSP is returned after exiting the handler mode i.e SVC handler is executed
	// R0 will contain the SVC number which can then be printed in thread mode by use of regsiter qualifier and prviding r0
	baseStack[0]=svc_number;


}

