/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  ******************************************************************************
*/

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include<stdio.h>
#include<stdint.h>
int main(void)
{
	// access the SCB and then the SHSCR for the cortex M4 processor
	uint32_t *pSHCRS=(uint32_t *)0xE000ED24; // pointer that points to a memory location at 0xE000ED24

	// enable the bits for mem manage,bus fault and usage fault
	*pSHCRS |= (1<<16);
	*pSHCRS |= (1<<17);
	*pSHCRS |= (1<<18);

	// execute an invalid function to evoke the fault handlers
	uint32_t *pSRAM=(uint32_t *)0x20010000;  // points to a memory location 0x200010000
	*pSRAM=0xFFFFFFFF; // stores an invalid OPCODE at the location 0x200010000

	void (*addr) (void);
	addr=(void *)0x20010001; // the last bit of the address has to be 1 since the Thumb bit is required to 1 if 0 then that is the ARM state- ARM instruction set is not supported and hence we get an error
	addr();


}

void BusFault_Handler()
{
	printf("Exception: Bus fault");
	while(1);
}

void MemManage_Handler()
{
	printf("Exception: Mem manage");
	while(1);
}

void UsageFault_Handler()
{
	uint32_t *pUFSR=(uint32_t *)0xE000ED2A;
	printf("Exception: Usage fault");
	printf("Status register for Usage fault = %lx\n",((*pUFSR)&0xFF));
	while(1);
}

void HardFault_Handler()
{
	printf("Exception: Hard fault");
	while(1);
}


